name: Run Python unittest

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

# don't cancel the running job when a new one is triggered
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # 支援的 Python 版本

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: Install Dependencies
      timeout-minutes: 20
      run: |
        python -m pip install --upgrade pip

    - name: Run Tests
      run: |
        python -m unittest discover -s test -p 'test_*.py'
